### ISSUE TITLE
Timeout Exception

### ISSUE THREAD

**Issue by 1bram** [alfonsrv/impf-botpy#10]
Hej, 
bot threw this exception, but continued running. Hope it wasn't a working appointment that got skipped. Haha.. But i guess Bot was waiting for page to load. But didn't? Dunno...

An unexpected exception occurred
Traceback (most recent call last):
  File "/Users/instabilothek/Documents/python/impf-botpy/impf/browser.py", line 315, in control_main
    self.confirm_eligible()
  File "/Users/instabilothek/Documents/python/impf-botpy/impf/browser.py", line 185, in confirm_eligible
    submit = self.wait.until(EC.element_to_be_clickable((By.XPATH, f'//button[@type="submit"]')))
  File "/Users/instabilothek/opt/anaconda3/lib/python3.7/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by yugret** [comment]
I had the same exception - it was on a working appointment and unfortunately the bot reloaded the window before I could put my information in...

**Comment by alfonsrv** [comment]
Hey, it was likely not an appointment – if this exception occurs the browser is trying to click on a button confirming you're in the person group allowed for vaccination. When the button is missing, resulting in this error, the bot skipped ahead prematurely – e.g. if you have a poor internet connection or the server is responding slowly.  

I added some code yesterday to make the workflow more robust; depends on the version you have. Can you check if you have `assert 'Gehören Sie einer impfberechtigten Personengruppen an?' in body.text` in your `impf/browser.py`?

edit: Just double checked – seems like there was an additional `submit` button command where it shouldn't have been. I just pushed a fix 8787cae – sorry! But don't worry, you'll get an appointment – I let it run to see if everything works and usually get at least 1 every two-three days.

**Comment by 1bram** [comment]
Thanks for quick fix and reply 👍

**Comment by alfonsrv** [comment]
:+1: should be ok now. If anything else should come up just fire an issue my way.
