### ISSUE TITLE
Step-by-step Link für Dummies funktioniert nicht

### ISSUE THREAD

**Issue by SarahausHH** [alfonsrv/impf-botpy#15]
Leider funktioniert der Link zur Step-by-Step für Dummies Anleitung nicht. Und ohne bin ich ziemlich hilflos...

**Comment by alfonsrv** [comment]
Ohne Details bisschen schwer was qualifiziertes zu sagen. Kannst Du bitte bereitstellen:

* *Was* funktioniert nicht?
* An welchem Schritt hast Du Probleme?
* Betriebssystem?

**Comment by SarahausHH** [comment]
Der Link in der Anleitung ergibt ein Error - Not Found

For Dummies
    I don't know anything about programming! And CLI gives me anxiety
Don't worry. It's easy. Follow **this** Step-by-Step Guide and then come back.

https://pythonrepo.com/alfonsrv/impf-botpy/blob/main/INSTALL.md

(Firefox und Chrome)

**Comment by alfonsrv** [comment]
Wie bist denn auf den Link gekommen? Bei mir öffnet's da: https://github.com/alfonsrv/impf-botpy/blob/main/docs/INSTALL.md

**Comment by SarahausHH** [comment]
Er steht hier im Text
https://pythonrepo.com/repo/alfonsrv-impf-botpy-python-miscellaneous#issues

Der, den Du hier gepostet hast, der funktioniert. Danke!

**Comment by alfonsrv** [comment]
Ah lol – das scheint irgendeine Spiegelseite zu sein, die sich ne 1:1 Kopie der originalen Seite erstellt.

Darüber habe ich keine Kontrolle. Die eigentliche Seite ist https://github.com/alfonsrv/impf-botpy/
