### ISSUE TITLE
No module named 'dataclasses'

### ISSUE THREAD

**Issue by xMAC94x** [alfonsrv/impf-botpy#17]
```
python3 main.py --code
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from impf.api import API
  File "/root/impf-botpy/impf/api.py", line 2, in <module>
    from dataclasses import dataclass, field
ModuleNotFoundError: No module named 'dataclasses'
```

do we need to add `dataclasses` in requierements ?

For others with the issues: quick workaround: ` pip3 install dataclasses`

**Comment by alfonsrv** [comment]
It sounds like you have an incomplete install. `dataclasses` is a [default](https://docs.python.org/3/library/dataclasses.html) Python 3.x package.

Make sure to follow the instructions in `docs/INSTALL.md`.
