### ISSUE TITLE
The State of Docker containers

### ISSUE THREAD

**Issue by alfonsrv** [alfonsrv/impf-botpy#27]
Been addressing it here and there, but wanted to centrally document the current state and issues when using Docker environments.

The main issue being that the bot is reliably flagged by ImpfterminService when running in Docker containers. It's basically unusable from my experience, as it's stuck with getting `429`s thrown at it. E.g. even after multiple hours it cannot enter the Vermittlungscode successfully – when reloading the page in the container and inputting it manually, it works first try. After that it can monitor for new appointments flawlessly – even though I haven't been able to get a successful alert from it yet.

Maybe some mouse wiggles can fix it. I'm a bit torn apart tho. While I want to solve it on a technical level, I think Docker containers only benefit a very small margin of people and it's likely an abuse-factor anyways.

**Comment by mod242** [comment]
Just wanted to let you know that I have been succesfull with the docker image in booking an appointment by replacing chromium with google-chrome inside the docker image. While I had 429s all the time before, after changing the browser this issue was gone and I was able to get an appointment after letting the bot run for about 24 hours. 

If you want to, I can open an PR (see https://github.com/mod242/impf-botpy/blob/main/docker/Dockerfile)

**Comment by alfonsrv** [comment]
Looks good. Interesting that fixed it for you. 

Sure, a PR is more than welcome! I also already thought about making the Chrome + Chromedriver version dynamic, as in auto-matching them. Chromedriver offers an [xml](https://chromedriver.storage.googleapis.com/) with `LATEST_RELEASE_version`

**Comment by Fr3shF1sh** [comment]
Hello
@alfonsrv @mod242
Thank you for updated Dockerfile. I can confirm it doesn't drop the shadowban error. 

Can you tell me how to connect to the docker VNC? I can't get a connection. Running docker inside a VM without gui.

**Comment by alfonsrv** [comment]
Please refer to [DOCKER.md](https://github.com/alfonsrv/impf-botpy/blob/main/docs/DOCKER.md)

**Comment by Fr3shF1sh** [comment]
thank you @alfonsrv. Not a dev so I struggled. But works now.
New Question / Hint:
do you think this option is helpful?
 network_mode: host

**Comment by mod242** [comment]
> Looks good. Interesting that fixed it for you.
> 
> Sure, a PR is more than welcome! I also already thought about making the Chrome + Chromedriver version dynamic, as in auto-matching them. Chromedriver offers an [xml](https://chromedriver.storage.googleapis.com/) with `LATEST_RELEASE_version`

I created #29 and took your idea to make the chromedriver version dynamic (based on the installed chrome-browser, not on latest release, to make sure it is in sync with what comes over the chrome-repos)

**Comment by alfonsrv** [comment]
Closing this. Thanks again for the great PR @mod242
