### ISSUE TITLE
Funktioniert Bot auch für "Weitere Impfzentren in NRW"?

### ISSUE THREAD

**Issue by TimB83** [alfonsrv/impf-botpy#30]
Hallo,

Sorry, falls diese Frage schon irgendwo beantwortet wurde: Funktioniert der Bot auch für Nordrhein-Westfalen bzw. die "Weiteren Impzentren in NRW"? Wenn man diese Möglichkeit auf impfterminservice.de auswählt, wird man ja weitergeleitet auf den Impfterminservice der Kassenärztlichen Vereinigung Nordrhein.

Für eine kurze Info wäre ich sehr dankbar.

**Comment by alfonsrv** [comment]
Hey @TimB83 – ne, sorry. NRW ist zwar gelistet, aber hat n komplett eigenes System gebaut. Können da leider nichts machen...

**Comment by TimB83** [comment]
Sehr schade :( Aber völlig verständlich. Herzlichen Dank für die superschnelle Reaktion, echt top!

**Comment by alfonsrv** [comment]
Gern ;)
