### ISSUE TITLE
sh: 1: espeak: not found

### ISSUE THREAD

**Issue by BruceGeLi** [alfonsrv/impf-botpy#35]
**Describe the issue**
Hi, I run "python3 main.py --alerts" and get (I hided my personal infomation):

[x] General
- Age: xxxxxxxxxxxxxxxxxxxxxxxx
- Mail: xxxxxxxxxxxxxxxxxxxxxxxx
- Mobile: xxxxxxxxxxxxxxxxxxxx
- Centers: 2 locations
[x] Remote Booking DISABLED
[x] Alerting Methods
- Custom Command ✓
2021-05-26 18:29:14,362 - [INFO] <impf.alert.alert.py:63>  Sending alert "Notification test from Impf Bot.py - https://github.com/alfonsrv/impf-botpy"
**sh: 1: espeak: not found**

**Versions**
Ubuntu 20.04,  Anaconda 4.8.3, Python 3.8.2 

Looks like the notification is not working, I have also tried installing the espeak my own, but I could not find a proper version of it. how can I solve this issue?

Thanks.

**Comment by alfonsrv** [comment]
`espeak` should come preinstalled with all Ubuntu Desktop versions. Otherwise simply use another text-to-speech program for your alerting command or one of the three supported messaging platforms.

**Comment by BruceGeLi** [comment]
Hi, thanks for your reply. 
I just found a solution through:
`sudo apt install espeak
sudo apt install espeak-ng-espeak`

**Comment by alfonsrv** [comment]
Hey @Fitz13009, alright! Next time please close the issue independently.
