### ISSUE TITLE
Booking an appointment sometime needs a page reload

### ISSUE THREAD

**Issue by lusor** [alfonsrv/impf-botpy#37]
I encountered this issue when I tried to book an appointment last week. impf-botpy alerted me to an available appointment and I then filled the form manually. However, the submit button was not enabled and I could not finish booking.

I then reloaded the page and the reserved appointment was still there (with the correct reservation time) and I now could book it successfully.

I suspect the issue is connected to the negative reservation time which is being displayed when using `RESCAN_APPOINTMENT`. The correct time is being displayed on the appointment popup, but not on the underlying page which will not be updated when the time ran out and new appointments are being searched for.

If this is a general issue and did not only happen to me, I'd suggest to do a page reload after an appointment was found and only then alert and potentially do the booking.

Cheers,
Volker

**Comment by alfonsrv** [comment]
I tend to consistently have a not-clickable booking button when the bot finds something. Usually clicking *Termine suchen* fixes it for me.  
A page reload may be undesirable as there's a considerable chance it will throw you back in the waiting room.

BR, Alfons

**Comment by lusor** [comment]
In my case clicking `Termine suchen` or `hier` did not solve the issue. One solution could be to check whether the button is clickable and reload if not. Or maybe it could be made clickable via Selenium?

**Comment by alfonsrv** [comment]
Closing because it's not relevant for the bot's process. Remote booking via API doesn't rely on the form's buttons to be clickable and if a user wants to book it manually they can judge themselves whether or not they want to reload the page.
