### ISSUE TITLE
Always loosing cookie bm_mi after some while

### ISSUE THREAD

**Issue by joef42** [alfonsrv/impf-botpy#39]
Hi,

I'm always loosing the bm_mi after some while of running the script. I first noticed this after an appointment was available, but the appointment did not fit for me so I didn't try booking it. However, I'm afraid that the next time I find an appointment I might have an issue booking it without the cookie so I quickly added the cookie check every time there is no appointment found. After starting the script it always looks fine, but after some while (could be an hour or only 15min) I suddenly start getting warnings about the missing cookie again.

I have a pretty default configuration. Only one location configured and I only changed BOOK_REMOTELY and SLEEP_NIGHT.

Wouldn't it be possible to always check the cookies and in case it is not valid anymore reload the page or something to get a refresh of the cookies? 

Version: 0.43b

Thanks.

**Comment by alfonsrv** [comment]
Hey @joggelxx, thanks for your feedback.  
It's not actually known which cookies are required for each step. I simply assumed `bm_mi` is necessary for successfully getting a Vermittlungscode.

Regarding actually booking appointments – don't worry. As soon as you're in the appointment search, no limitations seem to apply, so booking should work either way.

Hope that clears if up for you.

BR, Alfons

**Comment by joef42** [comment]
Great, thanks for the clarification. I will ignore the error from now on.

Regards,
Joe
