### ISSUE TITLE
Remote booking with telegram broken

### ISSUE THREAD

**Issue by joef42** [alfonsrv/impf-botpy#40]
Hi,

see
https://github.com/alfonsrv/impf-botpy/blob/aa0d228988d7cdcc3633fd7b38f033335c31916d/impf/alert.py#L124
https://github.com/alfonsrv/impf-botpy/blob/aa0d228988d7cdcc3633fd7b38f033335c31916d/impf/alert.py#L126

r was already parsed as Json, so it is already a dict and not a response anymore. 

Regards,
Joe

**Comment by alfonsrv** [comment]
Thanks for the heads up. Probably wasn't migrated properly after refactoring some code. Just pushed commit b28321d73224d2b89dd7581b89170e7d47ebcc38 to fix this.

BR,  
Alfons
