### ISSUE TITLE
Workflow geändert - Geburtstdatum statt Alter

### ISSUE THREAD

**Issue by fred922** [alfonsrv/impf-botpy#46]
Hallo,
erst mal allerbesten Dank fürs Programmieren.
Habe damit kurzfristig einen Termin für einen nahen Verwandten ergattern können.

Nach Wartungsarbeiten gestern Abend hat sich die Webseite bei Impfterminservice etwas geändert.

Um einen Vermittlungscode in der die Schnellprüfung zu erhalten wird dort nun nicht mehr nach dem Alter sondern nach dem Geburtsdatum gefragt.

Natürlich klappt damit die automat. Erkennung nicht mehr richtig und der Workflow stockt.
Gefragt wird nun: "Bitte geben Sie Ihr Geburtsdatum ein" Darunter ein Eingabefeld im Format tt.mm.jjjj

**Comment by alfonsrv** [comment]
Moin @fred922, cheers für die Info.
Sollte mit dem gestrigen Update schon adressiert worden sein: https://github.com/alfonsrv/impf-botpy/issues/44

**Comment by fred922** [comment]
funktioniert wieder.. vielen Dank !
