### ISSUE TITLE
Eingabe Geburtsdatum

### ISSUE THREAD

**Issue by lmfmaier** [alfonsrv/impf-botpy#48]
Ich kam heute morgen nach einigen Stunden mit dem Bot beim Server 001-iz zur Zuteilung einer Vermittlungscodes und da wurde dann ein Geburtsdatum abgefragt anstatt des Alters. Ich kann mich erinnern dass da früher eine Alterseingabe erschien, aber keine Datumseingabe. In der Config kann man ja nur das Alter eintragen. Jedenfalls kam der Bot bei dieser Eingabe nicht weiter. Habe leider keinen Screenshot o.ä.

**Comment by ChrizZz90** [comment]
Hi @lmfmaier, das Thema wurde hier in den vergangenen Tagen diskutiert und der Bot schon angepasst. Einfach die neuste Version nutzen und deine Settingsdatei anpassen. Die aktuelle Beispiel settings.py hat das Geburtsdatum integriert.

**Comment by lmfmaier** [comment]
> Hi @lmfmaier, das Thema wurde hier in den vergangenen Tagen diskutiert und der Bot schon angepasst. Einfach die neuste Version nutzen und deine Settingsdatei anpassen. Die aktuelle Beispiel settings.py hat das Geburtsdatum integriert.

Oh sorry, das mit der neuen Version ist mir entgangen

**Comment by alfonsrv** [comment]
So hoffe hat in Zwischenzeit jeder gesehen.
