### ISSUE TITLE
Crash when appointment is available without code

### ISSUE THREAD

**Issue by MarcelBochtler** [alfonsrv/impf-botpy#5]
It looks like the bot crashen when an appointment is available (without code):
```
2021-05-18 19:09:22,296 - [INFO] <impf.browser.browser.py:168>  71636: No longer in waiting room!
2021-05-18 19:09:53,950 - [ERROR] <impf.browser.browser.py:334>  71636: An unexpected exception occurred
Traceback (most recent call last):
  File "/home/marcel/workspace/impf-botpy/impf/browser.py", line 316, in control_main
    self.confirm_eligible()
  File "/home/marcel/workspace/impf-botpy/impf/browser.py", line 185, in confirm_eligible
    submit = self.wait.until(EC.element_to_be_clickable((By.XPATH, f'//button[@type="submit"]')))
  File "/home/marcel/.local/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

2021-05-18 19:09:54,082 - [INFO] <__main__.main.py:45>  Waiting until 19:14:54 before checking the next location
```

I checked this Impfzentrum at that time and was able to get a code. I doubt that this was an coincidence.

**Comment by alfonsrv** [comment]
The bot checks for certain elements to be there / to become available. This prevents the bot from running in an endless loop.  
In your case, the bot attempted to confirm that you are eligible but the button was no longer there.  

I assume you intervened manually, loading another page, this making the submit button become unavailable. 

Already considered allowing for more human interaction without having the bot crumbling down straight away.

**Comment by MarcelBochtler** [comment]
> I assume you intervened manually, loading another page, this making the submit button become unavailable.

I don't think so, I wasn't at the machine at the time.

**Comment by alfonsrv** [comment]
Looking at your other issue - another explanation could be the code skipping to this section prematurely due to a long server-response time. The code is checking if there is *no_vacancy*, but not if there actually *is* vacancy. I'll add some extra assertion checks to ensure the code does not skip to the next section prematurely when server responses are slow.

**Comment by MarcelBochtler** [comment]
The same issue occurred today.
I was not at my machine, saw the mentioned crash log in the terminal, tried with my phone and a slot was available again.

For me it looks like that the app is indeed crashing whenever a slot without a code is available (Anspruch prüfen).

I was using a version from this morning.

**Comment by alfonsrv** [comment]
You're right. I realized it today when https://github.com/alfonsrv/impf-botpy/issues/10 was submitted – probably a pasting error somewhere in the process.
