### ISSUE TITLE
ERROR bei  pip3 install -r requirements.txt --user

### ISSUE THREAD

**Issue by aschutt77** [alfonsrv/impf-botpy#50]
Hallo,

ich habe Probleme den Bot zum laufen zu bringen. Bisher habe ich mich an der Anleitung für Dummies entlanggehangelt. Bei der Eingabe des commands: 'pip3 install -r requirements.txt --user'  kommt es jedoch zu einer Fehlermeldung:

![Fehler 1](https://user-images.githubusercontent.com/85413346/120903305-c54af880-c645-11eb-899a-95eecb1bc956.png)

Habe zu Fehlerbehandlung folgendes probiert:
-löschen der Zeilen `cryptography` + `zulip` im file `requirements.txt`
-Python neu installieren mit den beschriebenen customized Einstellungen
-Update wie in der Fehlermeldung empfohlen mit 'python.exe -m pip install --upgrade pip' :  
![Fehler2](https://user-images.githubusercontent.com/85413346/120903611-5ff80700-c647-11eb-865b-d725221ce474.jpg)

-installieren von 'pip install chardet' 
-hinzufügen des Pfads 'C:\Users\---\AppData\Roaming\Python\Python39\Scripts' zu der Systemvariablen 'Path'

Die jetzige Fehlermeldung bei der Eingabe von  'pip3 install -r requirements.txt --user'  ist wie folgt: 

![Fehler 3](https://user-images.githubusercontent.com/85413346/120903707-fdebd180-c647-11eb-919e-3ec71cc6417c.png)

*****
C:\Users\---\Desktop\Impfbot\impf-botpy-main>pip3 install -r requirements.txt --user
Collecting certifi==2020.12.5
  Using cached certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
Collecting cffi==1.14.5
  Using cached cffi-1.14.5-cp39-cp39-win_amd64.whl (179 kB)
ERROR: Could not find a version that satisfies the requirement chardet==4.0.0Â´ (from versions: 1.0, 1.0.1, 1.1, 2.1.1, 2.2.1, 2.3.0, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 4.0.0)
ERROR: No matching distribution found for chardet==4.0.0Â´
*****

Mein Rechner läuft mit Windows 10, die Version des Bots ist denk ich die neueste (habe ihn vor 2-3 h runtergeladen).

Vielen Dank schonmal.

LG

**Comment by alfonsrv** [comment]
Haste denn mal probiert den Bot einfach auszuführen?

**Comment by alfonsrv** [comment]
Schätze mal es passt dann. 👍🏼

**Comment by aschutt77** [comment]
In der requirements.txt - Datei war ein Apostroph in der Chardet-Zeile eingetragen:
![WhatsApp Image 2021-06-06 at 11 21 10](https://user-images.githubusercontent.com/85413346/120921804-c885c900-c6c5-11eb-9c17-6970656bbf00.jpeg)

Ohne dieses hat die Installation geklappt. Jedoch klappt die Ausführung immernoch nicht: 

![Fehler 4](https://user-images.githubusercontent.com/85413346/120921865-37fbb880-c6c6-11eb-8b24-13590f15498b.png)

**Comment by alfonsrv** [comment]
Yo hast vermutlich n Tippfehler gemacht – Apostroph ist ja neben der Backspace-Taste.

Musst `settings.sample.py` in `settings.py` umbenennen. Einfach mal mit bisschen Geduld die Hauptseite und Anleitung für Dummies lesen.

**Comment by aschutt77** [comment]
Wahrscheinlich wars ein Tippfehler, gut dass ich ihn noch gefunden habe:)

Die Datei habe ich natürlich umbenannt:

![Fehler 5](https://user-images.githubusercontent.com/85413346/120922255-58c50d80-c6c8-11eb-9f93-1eb6ff850102.png)

**Comment by alfonsrv** [comment]
Musst die [Dateiendungen anzeigen](https://www.giga.de/tipp/windows-10-dateiendungen-anzeigen-so-gehts/). Deine `settings.py` heißt vermutlich `settings.py.py`

**Comment by aschutt77** [comment]
Das war der Fehler, vielen Dank da bin ich grad echt nicht draufgekommen. Vielen Dank auch für die Erstellung des Bots!
