### ISSUE TITLE
Problem after starting

### ISSUE THREAD

**Issue by grumpyp** [alfonsrv/impf-botpy#55]
**Describe the issue**
The bot was running for approx. 5 days without any luck so I decided to do an update and rerun it. It's now not working anymore.

**Versions**
Rasberry Pi, Version 0.46

**Log files**
```
pi@raspberrypi:~/Desktop/impf-botpy $ python3 main.py
2021-06-07 21:15:09,168 - [INFO] <__main__.main.py:117>  Starting up Impf Bot.py - github/@alfonsrv, 05/2021 (version 0.46)
[x] General
Traceback (most recent call last):
  File "main.py", line 121, in <module>
    print_config()
  File "main.py", line 22, in print_config
    print(f'- Birthday: {settings.BIRTHDATE}')
AttributeError: module 'settings' has no attribute 'BIRTHDATE'
```

**Comment by grumpyp** [comment]
In my settings.py is **no BIRTHDATE variable**, I changed it to  `print(f'- Birthday: {settings.AGE}')` and it works.

**Comment by mirkomack** [comment]
Pay attention that the Impfterminservice is now requiring the birthdate (dd.mm.yyyy) instead of the age. This is the reason why the AGE variable was replaced by the BIRTHDATE.
