### ISSUE TITLE
Troubleshooting Python was not found

### ISSUE THREAD

**Issue by Nico78HD** [alfonsrv/impf-botpy#56]
Hello
I have in cd line this error
C:\Users\user>python3 main.pypip3 install -r requirements.txt --user
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

I follow this instructions
You did not install Python properly. Either reinstall, following the steps or delete the python.exe and python3.exe in %LocalAppData%\Microsoft\WindowsApps

BUT I can't delete python.exe & python3.exe in %LocalAppData%\Microsoft\WindowsApps
I add the windows message in attachement.
![fehler](https://user-images.githubusercontent.com/85539607/121123395-73f86000-c823-11eb-8ebd-fb448c46a38c.PNG)

I running win10 as adminstrator
I reinstall Python with the link provide in this page

Any advise ?

Thanks a lot

**Comment by ghost** [comment]
Try to run `pip install -r requirements.txt` and than just `main.py`

**Comment by Nico78HD** [comment]
> Try to run `pip install -r requirements.txt` and than just `main.py`

Thanks, that what I get now :(
C:\Users\user>pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
WARNING: You are using pip version 21.1.1; however, version 21.1.2 is available.
You should consider upgrading via the 'c:\program files\python38\python.exe -m pip install --upgrade pip' command.

C:\Users\user>main.py
Der Befehl "main.py" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

C:\Users\user>

**Comment by ghost** [comment]
Well you have to go to the right directory first. Use `cd pathToYourImpfBotFolder` in the command window. Than use the commands above.

**Comment by Nico78HD** [comment]
> Well you have to go to the right directory first. Use `cd pathToYourImpfBotFolder` in the command window. Than use the commands above.

**I'm not a Informatic guy, I'm a little bit lost in this workflow.
I tried this different step** : 

C:\Users\user>cd Downloads/impf-botpy-main
Das System kann den angegebenen Pfad nicht finden.

C:\Users\user>pip3 install -r requirements.txt --user
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
WARNING: You are using pip version 21.1.1; however, version 21.1.2 is available.
You should consider upgrading via the 'c:\program files\python38\python.exe -m pip install --upgrade pip' command.

C:\Users\user>pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
WARNING: You are using pip version 21.1.1; however, version 21.1.2 is available.
You should consider upgrading via the 'c:\program files\python38\python.exe -m pip install --upgrade pip' command.

C:\Users\user>cd pathToYourImpfBotFolder
Das System kann den angegebenen Pfad nicht finden.

C:\Users\user>Downloads/impf-botpy-main
Der Befehl "Downloads" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

C:\Users\user>pip3 install -r requirements.txt --user
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
WARNING: You are using pip version 21.1.1; however, version 21.1.2 is available.
You should consider upgrading via the 'c:\program files\python38\python.exe -m pip install --upgrade pip' command.

C:\Users\user>python3 main.pycd pathToYourImpfBotFolder
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

C:\Users\user>

**Comment by ghost** [comment]
I guess you put the ImpfBot folder into the Downloads folder. So the correct path is likely: C:\Users\user\Downloads\impf-botpy-main. The workflow should be

`cd C:\Users\user\Downloads\impf-botpy-main`
`pip install -r requirements.txt`
`main.py`

**Comment by Nico78HD** [comment]
> `cd C:\Users\user\Downloads\impf-botpy-main`
> `pip install -r requirements.txt`
> `main.py`

**Some progress :)**  Thank you!!! and now? sorry for this questions
C:\Users\user\Downloads\impf-botpy-main>pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Collecting certifi==2020.12.5
  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
     |████████████████████████████████| 147 kB 1.6 MB/s
Collecting cffi==1.14.5
  Downloading cffi-1.14.5-cp38-cp38-win_amd64.whl (179 kB)
     |████████████████████████████████| 179 kB 1.7 MB/s
Collecting chardet==4.0.0
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
     |████████████████████████████████| 178 kB 1.7 MB/s
Collecting distro==1.5.0
  Downloading distro-1.5.0-py2.py3-none-any.whl (18 kB)
Collecting idna==2.10
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 1.2 MB/s
Collecting matrix-client==0.3.2
  Downloading matrix_client-0.3.2-py2.py3-none-any.whl (28 kB)
Collecting pycparser==2.20
  Downloading pycparser-2.20-py2.py3-none-any.whl (112 kB)
     |████████████████████████████████| 112 kB 2.2 MB/s
Collecting pyOpenSSL==20.0.1
  Downloading pyOpenSSL-20.0.1-py2.py3-none-any.whl (54 kB)
     |████████████████████████████████| 54 kB 1.3 MB/s
Collecting requests==2.25.1
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 1.3 MB/s
Collecting selenium==3.141.0
  Downloading selenium-3.141.0-py2.py3-none-any.whl (904 kB)
     |████████████████████████████████| 904 kB 1.3 MB/s
Collecting six==1.16.0
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting urllib3==1.26.4
  Downloading urllib3-1.26.4-py2.py3-none-any.whl (153 kB)
     |████████████████████████████████| 153 kB 1.3 MB/s
Collecting cryptography>=3.2
  Downloading cryptography-3.4.7-cp36-abi3-win_amd64.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 1.6 MB/s
Installing collected packages: pycparser, urllib3, idna, chardet, cffi, certifi, six, requests, cryptography, selenium, pyOpenSSL, matrix-client, distro
  WARNING: The script chardetect.exe is installed in 'C:\Users\user\AppData\Roaming\Python\Python38\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script distro.exe is installed in 'C:\Users\user\AppData\Roaming\Python\Python38\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed certifi-2020.12.5 cffi-1.14.5 chardet-4.0.0 cryptography-3.4.7 distro-1.5.0 idna-2.10 matrix-client-0.3.2 pyOpenSSL-20.0.1 pycparser-2.20 requests-2.25.1 selenium-3.141.0 six-1.16.0 urllib3-1.26.4
WARNING: You are using pip version 21.1.1; however, version 21.1.2 is available.
You should consider upgrading via the 'c:\program files\python38\python.exe -m pip install --upgrade pip' command.

C:\Users\user\Downloads\impf-botpy-main>main.py

**Comment by alfonsrv** [comment]
Please follow and read [INSTALL.md](https://github.com/alfonsrv/impf-botpy/blob/main/docs/INSTALL.md) again. Take your time.
