### ISSUE TITLE
format birthday is changed ??

### ISSUE THREAD

**Issue by Nico78HD** [alfonsrv/impf-botpy#65]
Is it possible that the birthday format has changed ?
I think it was before : DD/MM/YYYY 
Now : MM/DD/YYYY

When the robots is in this pages, I've never get a SMS-code. 
Perhaps this is the raison
Thanks
![0000000](https://user-images.githubusercontent.com/85539607/121707787-3cb1d980-cad7-11eb-9509-ab64619920de.PNG)

**Comment by jonaskuske** [comment]
It's `TT.mm.jjjj` for me – afaik it's localized, so you might want to check your environment. (Docker container with wrong locale?)

**Comment by Nico78HD** [comment]
> It's `TT.mm.jjjj` for me – afaik it's localized, so you might want to check your environment. (Docker container with wrong locale?)
Thanks Jonaskuske
And how can you check the environment ? 
Nicolas

**Comment by EricDuminil** [comment]
Is exact birthday even relevant? I think it's just used to determine which vaccine is proposed. I simply write 01/01/1990, then I don't care if it's DD/MM or MM/DD.
