### ISSUE TITLE
ModuleNotFoundError: No module named 'selenium'

### ISSUE THREAD

**Issue by HenStar48** [alfonsrv/impf-botpy#7]
Just installed the bot with help of the newbie guide but I get the Error:
"ModuleNotFoundError: No module named 'selenium'" when trying to start.
Any idea how to fix this?

Thanks for your work!

**Comment by alfonsrv** [comment]
Please follow the [INSTALL.md](https://github.com/alfonsrv/impf-botpy/blob/main/docs/INSTALL.md) - you're missing the Python libraries (`pip install -r requirements.txt --user`)

**Comment by HenStar48** [comment]
If I type the pip install command it says "Requirement already satisfied"

<img width="454" alt="Bild1" src="https://user-images.githubusercontent.com/84408638/118704728-baa3fd00-b817-11eb-91e9-6d9bd85c8ed2.png">

**Comment by alfonsrv** [comment]
Ah I see. You probably have two Versions of Python installed - Python2 and Python3. Try running again with `pip3`

edit: even though the output shows it's apparently installed in the `python3.8` folder.  

A few things to try here:
- Check if it makes any difference if you do not add the `--user`. You will likely have to start `cmd.exe` as Administrator to run the command without any errors.
- alternatively you should add your library path (`%AppData%\Python\Python38\Site-Packages`) to your [%PATH% variable](https://java.com/en/download/help/path.html) (tutorial for Java, but also applies for Python)

**Comment by HenStar48** [comment]
I uninstalled the Phython 2 Version and now everything works fine.
Thanks a lot!
